#!/bin/bash
source $OPENSHIFT_CARTRIDGE_SDK_BASH

# The logic to stop your application should be put in this script.
if ! killall -0 elasticsearch
then
    client_result "Application is already stopped"
else
    killall -INT elasticsearch
fi
